version: '2'
services:
#  rabbitmqdocker:
#    hostname: rabbitmqdocker
#    image: "rabbitmq:3.7.7-management"
#    ports:
#      - "15672:15672"
#      - "5672:5672"
  orderservice:
    image: order-service:v1
    ports:
      - "8081:8081"
    environment:
      SECOND_SERVICE_URI: "http://orderprocessorservice:8082/"
  redis:
      image: redis:alpine
      ports:
        - 6379:6379
#  orderprocessorservice:
#    image: order-processor-service:v1
#    ports:
#      - "8082:8082"
#  zuulproxy:
#        image: zuul-proxy:v1
#        ports:
#          - "8080:8080"
#  authserver:
#        image: auth-server:v1
#        ports:
#          - "5555:5555"