version: '2'
services:
  orderservice:
    image: order-service:v1
    ports:
      - "8081:8081"
    environment:
          SECOND_SERVICE_URI: "http://orderprocessorservice:8082/"
  orderprocessorservice:
      image: order-processor-service:v1
      ports:
        - "8082:8082"
#  zuulproxy:
#        image: zuul-proxy:v1
#        ports:
#          - "8080:8080"
#  authserver:
#        image: auth-server:v1
#        ports:
#          - "5555:5555"