server:
  port: 8080

zuul:
  routes:
    hello-service:
      path: /hello/**
      url: http://127.0.0.1:8081/
    second-service:
        path: /second/**
        url: http://127.0.0.1:8082/
    google:
      path: /
      url: http://www.google.com