server:
  port: 8080

zuul:
  routes:
    hello-service:v1:
      path: /hello/**
      url: http://orderapplication:8081/
    second-service:v1:
        path: /second/**
        url: http://second-service:8082/
    google:
      path: /
      url: http://www.google.com